import java.io.IOException;

public class FormatDemo1
{

	/*
	 * The i and r variables are formatted twice: the first
	 * time using code in an overload of print, the second
	 * time by conversion code automatically generated by
	 * the Java compiler, which also utilizes toString. You
	 * can format any value this way, but you don't have
	 * much control over the results.
	 */
	public static void main(String[] args) throws IOException
	{
		int i = 5;
		double r = Math.sqrt(i);

		/*
		 * Invoking print or println outputs a single value
		 * after converting the value using the appropriate
		 * toString method
		 */
		System.out.print("The square root of ");
		System.out.print(i);
		System.out.print(" is ");
		System.out.print(r);
		System.out.println(".");

		i = 10;
		r = Math.sqrt(i);
		System.out.println("The square root of " + i + " is " + r + ".");

	}
}
